package com.simplestructurescanner.structure.pillar;

import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.datafix.DataFixer;
import net.minecraft.world.World;
import net.minecraft.world.WorldProvider;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.chunk.storage.IChunkLoader;
import net.minecraft.world.gen.structure.template.TemplateManager;
import net.minecraft.world.storage.IPlayerFileData;
import net.minecraft.world.storage.ISaveHandler;
import net.minecraft.world.storage.WorldInfo;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.io.File;

/**
 * A save handler for the structure validation world that performs no actual save operations.
 * This prevents the fake world from writing any data to disk.
 *
 * Implements:
 * - ISaveHandler: Main save handler interface
 * - IPlayerFileData: Player data management (no-op)
 * - IChunkLoader: Chunk loading/saving (no-op)
 *
 * All methods return safe default values or perform no-ops to prevent
 * the validation world from affecting the real game state.
 */
public class ValidationSaveHandler implements ISaveHandler, IPlayerFileData, IChunkLoader {

    private static final String[] NO_PLAYER_DATA = new String[0];

    @Override
    public WorldInfo loadWorldInfo() {
        // Return null - the fake world creates its own WorldInfo
        return null;
    }

    @Override
    public void checkSessionLock() {
        // No-op - validation world doesn't need session locking
    }

    @Nonnull
    @Override
    public IChunkLoader getChunkLoader(@Nonnull WorldProvider provider) {
        // Return self as the chunk loader
        return this;
    }

    @Nonnull
    @Override
    public IPlayerFileData getPlayerNBTManager() {
        // Return self as the player data manager
        return this;
    }

    @Nonnull
    @Override
    public TemplateManager getStructureTemplateManager() {
        // Return a new template manager with a no-op data fixer
        return new TemplateManager("", new DataFixer(0));
    }

    @Override
    public void saveWorldInfoWithPlayer(@Nonnull WorldInfo worldInformation, @Nonnull NBTTagCompound tagCompound) {
        // No-op - don't save anything
    }

    @Override
    public void saveWorldInfo(@Nonnull WorldInfo worldInformation) {
        // No-op - don't save anything
    }

    @Nullable
    @Override
    public File getWorldDirectory() {
        // Return null - validation world has no directory
        return null;
    }

    @Nullable
    @Override
    public File getMapFileFromName(@Nonnull String mapName) {
        // Return null - validation world doesn't save maps
        return null;
    }

    @Nullable
    @Override
    public Chunk loadChunk(@Nonnull World worldIn, int x, int z) {
        // Return null - chunks are generated by ValidationChunkProvider, not loaded
        return null;
    }

    @Override
    public void saveChunk(@Nonnull World worldIn, @Nonnull Chunk chunkIn) {
        // No-op - don't save chunks
    }

    @Override
    public void saveExtraChunkData(@Nonnull World worldIn, @Nonnull Chunk chunkIn) {
        // No-op - don't save extra chunk data
    }

    @Override
    public void chunkTick() {
        // No-op - validation world doesn't tick
    }

    @Override
    public void flush() {
        // No-op - nothing to flush
    }

    @Override
    public boolean isChunkGeneratedAt(int x, int z) {
        // Return false - let the chunk provider handle this
        return false;
    }

    // Player data methods (all no-ops for validation world)

    @Override
    public void writePlayerData(@Nonnull EntityPlayer player) {
        // No-op - don't save player data
    }

    @Nullable
    @Override
    public NBTTagCompound readPlayerData(@Nonnull EntityPlayer player) {
        // Return null - no player data to load
        return null;
    }

    @Nonnull
    @Override
    public String[] getAvailablePlayerDat() {
        // Return empty array - no players in validation world
        return NO_PLAYER_DATA;
    }
}
